routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Auth::routes();

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/home', 'HomeController@index');

Route::group(['prefix' => 'admin', 'middleware' => ['role:admin|manager']], function() {
    Route::get('/', 'AdminController@index')->name('admin');
    Route::resource('/users', 'UserController');

    Route::get('/users/{username}/activity', 'ActivityController@show')->name('admin.user.activity');
    Route::get('/activity', 'ActivityController@all')->name('admin.activity');
    Route::get('/roles/{role}/permissions', 'UserController@getPermissionsAttachedToRole')->name('users.roles.permissions');
});

resources/views/partials/admin/menu.blade.php
<li class="dropdown">
    <a href="#" class="dropdown-toggle"
       data-toggle="dropdown"
       role="button"
       aria-haspopup="true"
       aria-expanded="false">
        Management
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <li><a href="{{route('users.index')}}">Users</a></li>
        <li role="separator" class="divider"></li>
        <li><a href="{{route('admin.activity')}}">Activity</a></li>
    </ul>
</li>