routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Auth::routes();

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/home', 'HomeController@index');

Route::group(['prefix' => 'admin', 'middleware' => ['role:admin|manager']], function() {
    Route::get('/', 'AdminController@index')->name('admin');
    Route::resource('/users', 'UserController');

    Route::get('/users/{username}/activity', 'ActivityController@show')->name('admin.user.activity');
    Route::get('/activity', 'ActivityController@all')->name('admin.activity');
    Route::get('/roles/{role}/permissions', 'UserController@getPermissionsAttachedToRole')->name('users.roles.permissions');
});

app/User.php
<?php

namespace App;

use App\Traits\RecordsActivity;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Authenticatable
{
    use RecordsActivity;
    use EntrustUserTrait;
    use Notifiable;

    /**
     * Validate Rules
     * 
     * @return array
     */
    public static function rules(){
        return [
            'name' => 'required|min:3|max:15',
            'email' => 'required|email|unique:users,email',
            'password' => 'nullable|min:8|max:25'
        ];
    }
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Get all perms
     *
     * @return array
     */
    public function getAllPermissions()
    {

        $perms = [];
        $roles = $this->roles()->get();

        foreach ($roles as $role) {
            foreach($role->perms as $perm){
                array_push($perms,$perm);
            }
        }
        return $perms;
    }

    /**
     * Get an Array of User's Permissions Ids
     * 
     * @return array
     */
    public function getPermissionsIds(){
        $ids = [];
        $perms = $this->getAllPermissions();
        foreach($perms as $perm){
            array_push($ids, $perm->id);
        }
        return $ids;
    }

    /**
     * Return Users's Activity
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function activity()
    {
        return $this->hasMany('App\Activity');
    }

    /**
     * Return Users's Activity
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function authlog()
    {
        return $this->hasMany('App\AuthLog');
    }
    
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Role;
use App\Permission;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('validate.user', ['only' => ['store','update']]);
    }

    /**
     * Show Admin Index
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $users = (new User)::paginate(10);
        return view('users.index', compact('users'));
    }

    /**
     * Edit User
     *
     * @param User $user
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(User $user)
    {
        $roles = (new Role)::get()->pluck('name', 'id');
        $permissions = $user->getAllPermissions();
        return view('users.show', compact('user', 'roles', 'permissions'));
    }

    /**
     * Edit User Frm
     *
     * @param User $user
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(User $user)
    {
        $roles = (new Role)::get()->pluck('name', 'id');
        $permissions = $user->getAllPermissions();
        return view('users.edit', compact('user', 'roles', 'permissions'));
    }

    /**
     * Create User Frm
     *
     * @param User $user
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create(User $user)
    {
        $roles = (new Role)::get()->pluck('name', 'id');
        $permissions = Role::first()->permissions()->get();
        return view('users.create', compact('user', 'roles', 'permissions'));
    }

    /**
     * User Store
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $user = User::create(hasPasswordCryptOrRemove($request));
        $role = Role::findOrFail($request->input('roles'));
        $user->attachRole($role);
        return redirect()->to(route('users.show', ['user' => $user->id]));
    }

    /**
     * Update a User
     *
     * Validated by UserValidate Middleware
     *
     * hasPasswordCryptOrRemove Support/Helpers
     * @param Request $request
     * @param User $user
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(Request $request, User $user)
    {
        if($request->input('roles')) {
            $role = Role::findOrFail($request->input('roles'));
            $user->detachRoles($user->roles);
            $user->attachRole($role);
        }

        $user->update(hasPasswordCryptOrRemove($request));
        flash('User Updated', 'info');
        return redirect()->back();
    }

    /**
     * Delete User
     *
     * @param User $user
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy(User $user)
    {
        //do not allow to delete it self
        if (Auth::user()->id == $user->id) {
            flash('Not Allowed to Destroy your Self', 'danger')->important();
            return redirect()->back();
        }

        //Delete User
        $user->delete();
        flash('User Deleted', 'info');
        return redirect()->route('users.index');
    }

    /**
     * Update User Role
     *
     * @param Request $request
     * @param User $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function userRolesUpdate(Request $request, User $user)
    {
        $role = Role::findOrFail($request->input('roles'));
        $user->detachRoles($user->roles);
        $user->attachRole($role);
        flash('User Role Update', 'info');
        return redirect()->back();
    }

    /**
     * Get permissions attached to Role
     *
     * @param Role $role
     * @return \Illuminate\Http\JsonResponse
     */
    public function getPermissionsAttachedToRole(Role $role)
    {
        return response()->json($role->permissions()->get());
    }
}

resources/views/partials/users/create.blade.php
{!! Form::open(['method' => 'POST', 'url' => route('users.store')])!!}

@include('partials.users.frm', ['submit' => 'Create User'])

{!! Form::close() !!}

resources/views/partials/users/deleteFrm.blade.php
<div class="row">
    <div class="col-md-9 col-md-offset-3">
        {!! Form::model($user,
                                [
                                  'method' => 'DELETE',
                                  'url' => route('users.destroy', ['id' => $user->id])
                                ])
                               !!}
        <button class="btn btn-danger btn-lg" type="submit">
            Delete User
        </button>
        {!! Form::close() !!}

    </div>
</div>

resources/views/partials/users/deleteModalConfirmation.blade.php
<div id="deleteModalConfirmation" class="modal fade"
     tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">

    <div class="modal-dialog modal-sm" role="document">

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"
                        data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
               <h2 class="text-center text-info">Confirmation Please</h2>
            </div>

            <div class="modal-body">
                @include('partials.users.deleteFrm')
            </div>

            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>

resources/views/partials/users/editFrm.blade.php
{!! Form::model($user,['method' => 'PATCH',
                       'url' => route('users.update', ['id' => $user->id])])!!}

@include('partials.users.frm', ['submit' => 'Edit User'])

{!! Form::close() !!}

resources/views/partials/users/frm.blade.php
<div class="form-group">
    {!! Form::label('name', 'Name') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('email', 'Email') !!}
    {!! Form::text('email', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('password', 'Password') !!}
    {!! Form::text('password', '', ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    @include('partials.users.rolesSelect')
</div>

<div class="form-group">
    <h4>Permissions</h4>
    <div class="list-group" id="user_permissions">
        @foreach($permissions as $permission)
            <li class="list-group-item">{{ $permission->name }}</li>
        @endforeach
    </div>
</div>

<button class="btn btn-success" type="submit">
    {{$submit}}
</button>

resources/views/partials/users/listItem.blade.php
<a href="{{route('users.show',['id' => $user->id])}}" class="list-group-item">
    <h4>{{ $user->name }}</h4>
    <p>Email: {{ $user->email }}</p>
    @each('partials.users.roles.item', $user->roles()->get(), 'role', 'partials.users.roles.empty')
</a>

resources/views/partials/users/permissionsSelect.blade.php
{!! Form::label('Permissions', 'Permissions') !!}
{!! Form::select(
                'Permissions',
                $permissions ,
                $user->getPermissionsIds(),
                ['multiple' => true],
                ['class' => 'form-control']
    )
                !!}

resources/views/partials/users/rolesFrm.blade.php
{!! Form::model($user, ['url' => route('admin.userRoles.update',['id' => $user->id]),
 'class' => 'form']) !!}

<div class="form-group">
    @include('partials.users.rolesSelect')
</div>

<div class="form-group">
    <h4>Permissions</h4>
    <div class="list-group" id="user_permissions">
        @foreach($permissions as $permission)
            <li class="list-group-item">{{ $permission->name }}</li>
        @endforeach
    </div>
</div>

<button class="btn btn-success" type="submit">
    Edit User
</button>

{!! Form::close() !!}

resources/views/partials/users/rolesSelect.blade.php
{!! Form::label('Roles', 'Roles') !!}
{!! Form::select('roles',
                 $roles ,
                 count($user->roles()->get()) > 0 ? $user->roles()->get()[0]->id : null,
                 ['class' => 'form-control'])
!!}